### ISSUE TITLE
Accept balance in decimals 

### ISSUE THREAD

**Issue by adi50920** [Google-DSC-DMCE/Expense-Tracker-HacktoberFest-2023#1]
Let the input field accept decimals and round it off to 2 decimal places

**Comment by Anemaygi** [comment]
Hello, can you assign this issue to me?

I've created a pull request for that,  I'm rounding it off to 2 decimals places, but I think the input field already accepts decimals, does not it? If something is wrong, feel free to let me know and I'll fix it!

**Comment by adi50920** [comment]
> Hello, can you assign this issue to me?
> 
> 
> 
> I've created a pull request for that,  I'm rounding it off to 2 decimals places, but I think the input field already accepts decimals, does not it? If something is wrong, feel free to let me know and I'll fix it!
> 
> 
> 
> 

Yes, the input field accepts decimals upto any number, so you just had to round the total balance to 2 decimals and after reviewing your pull request it seems you have correctly done it.
