### ISSUE TITLE
Create a Better UI 

### ISSUE THREAD

**Issue by adi50920** [Google-DSC-DMCE/Expense-Tracker-HacktoberFest-2023#2]
Change styles to have a more modern UI

**Comment by Tarunkumarchelumalla** [comment]
Assign this to me @adi50920

**Comment by adi50920** [comment]
> Assign this to me @adi50920

Assigned

**Comment by Tarunkumarchelumalla** [comment]
completed the task a look at this pr:-https://github.com/Google-DSC-DMCE/Expense-Tracker-HacktoberFest-2023/pull/20
