### ISSUE TITLE
Fix balance going negative

### ISSUE THREAD

**Issue by adi50920** [Google-DSC-DMCE/Expense-Tracker-HacktoberFest-2023#5]
The total balance is going negative. Add an Alert saying "You don't have enough balance", and make sure balance never goes negative

**Comment by gaurangbiyani-2021** [comment]
Please assign it to me

**Comment by adi50920** [comment]
> Please assign it to me 
> 
> 

sure go ahead

**Comment by gaurangbiyani-2021** [comment]
issue resolved.
