### ISSUE TITLE
Separate input buttons for income and expense 

### ISSUE THREAD

**Issue by adi50920** [Google-DSC-DMCE/Expense-Tracker-HacktoberFest-2023#9]
Add two separate buttons : 
a. add the amount to the balance(income) 
b. deduce the amount from the balance and add it to expense(expense)

**Comment by mtahashahid** [comment]
Hey,  I want to work on this issue.
Can you assign this to me

**Comment by adi50920** [comment]
> Hey, I want to work on this issue. Can you assign this to me

sure, go ahead

**Comment by karankoder** [comment]
@adi50920  Can you assign this issue to me?

**Comment by adi50920** [comment]
> @adi50920 Can you assign this issue to me?

Sure go ahead

**Comment by Orange-Tofu** [comment]
@adi50920 since its been more than week and karan did not make a pull request. Therefore a created a PR.
